### ISSUE TITLE
Forge v0.0.5 Crashes with Fire Emblem Three Houses v1.1.0

### ISSUE THREAD

**Issue by shay-henderson-mscst** [three-houses-research-team/Starfall#2]
I'm using Kosmos with Forge 0.0.5 with FETH v1.1.0 and it crashes upon launching the game every time. I'm unsure what to do as I would rather not update FE to 1.1.1 although Forge works with that version.

**Comment by Raytwo** [comment]
Mhhhh, as far as I remember, Forge had no issue with FETH v1.1.0, in fact, some people from DeathChaos' server used it just fine, me included.
I can understand not wanting to update your game though, but considering that update changes close to nothing, you can probably update safely to 1.1.1 without breaking your mods.

**Comment by neptuwunium** [comment]
FETH 1.1.1 only updates DLC. All major exefs patches and cheats have been updated already.

**Comment by shay-henderson-mscst** [comment]
I'm using a save editor from gbatemp that isn't updated for 1.1.1 currently. I tried using Forge for 1.1.0 again with the same results. Not sure what I'm doing wrong but it's just crashing right after launching the game.

**Comment by shay-henderson-mscst** [comment]
Nevermind, found a working Editor on an old SSD that works for 1.1.1 and NG+ save files.

I've updated FETH and Forge to 1.1.1, everything is working now.
